Feat/rush init project default value
bytesfriends/rush-plugins pull request #38
Opened 2022-11-22 09:37 UTC by nanaSun

### Basic Checks

Have you run `rush change` for this change?

- [x] Yes
- [ ] No

If **No**, please run `rush change` before, this is necessary.

If adding a **new feature**, the PR's description includes:

- [x] Reason for adding this feature
- [x] How to use
- [x] A basic example

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

### Summary
Take git user.name as default authorName.
And set default folders for user to choose.

### Detail

<img width="663" alt="default git user.name" src="https://user-images.githubusercontent.com/29034500/203279103-bac4c8a2-7d37-4297-bd37-b5808bc6e5df.png">

<img width="576" alt="choose folder" src="https://user-images.githubusercontent.com/29034500/203279149-68d532af-c5a4-4b74-9bf9-eec727b03602.png">

### How to test it

2022-11-22 09:42 UTC, chengcyber requested changes

2022-11-22 09:42 UTC, chengcyber commented on rush-plugins/rush-init-project-plugin/src/logic/GitConfig.ts
> +  const result: child_process.SpawnSyncReturns<Buffer> =  child_process.spawnSync(
这里需要加个 try-catch，处理下异常情况

2022-11-22 09:42 UTC, chengcyber commented on rush-plugins/rush-init-project-plugin/src/logic/GitConfig.ts
> +    stdio: ['pipe', 'pipe', 'pipe'],
这样的话，user name 会打印出来？ 好像不需要打印

2022-11-22 09:42 UTC, chengcyber commented on rush-plugins/rush-init-project-plugin/src/logic/GitConfig.ts
> +  return result.stdout.toString()??'';
感觉缺了 format...

2022-11-22 09:42 UTC, chengcyber commented on rush-plugins/rush-init-project-plugin/src/plopfile.ts
> +      default(){
```suggestion
      default() {
```

2022-11-22 10:57 UTC, nanaSun commented on rush-plugins/rush-init-project-plugin/src/logic/GitConfig.ts
> +  return result.stdout.toString()??'';
done

2022-11-22 10:57 UTC, nanaSun commented on rush-plugins/rush-init-project-plugin/src/plopfile.ts
> +      default(){
done

2022-11-22 10:57 UTC, nanaSun commented on rush-plugins/rush-init-project-plugin/src/logic/GitConfig.ts
> +  const result: child_process.SpawnSyncReturns<Buffer> =  child_process.spawnSync(
done

2022-11-23 06:26 UTC, chengcyber approved these changes

2022-11-23 06:27 UTC, merged